version: '3'
volumes:
    mongo-data:
        driver: local
        name: mongo-data
services:
    app: 
        build:
            context: .
            dockerfile: Dockerfile
        command: sleep infinity
        volumes:
            - .:/home/app/
        network_mode: service:mongodb

    mongodb:
        image: mongo
        ports:
            - 27017:27017
        environment:
            - MONGO_INITDB_ROOT_USERNAME=admin
            - MONGO_INITDB_ROOT_PASSWORD=password
        volumes:
            - mongo-data:/data/db

    mongo-express:
        image: mongo-express
        ports:
            - 8081:8081
        restart: unless-stopped
        environment:
            - ME_CONFIG_MONGODB_ADMINUSERNAME=admin    
            - ME_CONFIG_MONGODB_ADMINPASSWORD=password
            - ME_CONFIG_MONGODB_SERVER=mongodb
  